theme: jekyll-theme-slate

title: [Graphitti](https://jbrown725.github.io/)
description: A project to facilitate construction of high-performance neural simulations
baseurl: /docs

show_downloads: false
